import React, { useState, useEffect } from 'react';
import {
  Code2, FolderTree, Terminal as TerminalIcon, Play, Bug, FileCode,
  Sparkles, RefreshCw, TestTube, Save, ChevronRight, ChevronDown, File
} from 'lucide-react';
import { cn } from '../lib/utils';
import { api } from '../lib/api';

interface FileNode {
  name: string;
  path: string;
  type: 'file' | 'directory';
  children?: FileNode[];
  language?: string;
}

const SAMPLE_TREE: FileNode = {
  name: 'arcange-ai-assistant',
  path: '.',
  type: 'directory',
  children: [
    {
      name: 'frontend',
      path: 'frontend',
      type: 'directory',
      children: [
        { name: 'App.tsx', path: 'frontend/App.tsx', type: 'file', language: 'typescript' },
        { name: 'main.tsx', path: 'frontend/main.tsx', type: 'file', language: 'typescript' },
        {
          name: 'components',
          path: 'frontend/components',
          type: 'directory',
          children: [
            { name: 'ChatPanel.tsx', path: 'frontend/components/ChatPanel.tsx', type: 'file', language: 'typescript' },
            { name: 'Sidebar.tsx', path: 'frontend/components/Sidebar.tsx', type: 'file', language: 'typescript' },
          ],
        },
      ],
    },
    {
      name: 'desktop-agent',
      path: 'desktop-agent',
      type: 'directory',
      children: [
        { name: 'main.py', path: 'desktop-agent/main.py', type: 'file', language: 'python' },
        { name: 'config.py', path: 'desktop-agent/config.py', type: 'file', language: 'python' },
      ],
    },
    { name: 'package.json', path: 'package.json', type: 'file', language: 'json' },
  ],
};

const SAMPLE_CODE = `import React from 'react';
import { Sparkles } from 'lucide-react';

export const ArcangeComponent = () => {
  return (
    <div className="arcange-container">
      <Sparkles className="w-6 h-6 text-blue-400" />
      <h1>Arcange AI Assistant</h1>
    </div>
  );
};`;

export const CodingPanel: React.FC = () => {
  const [tree, setTree] = useState<FileNode>(SAMPLE_TREE);
  const [expandedDirs, setExpandedDirs] = useState<Set<string>>(new Set(['.', 'frontend']));
  const [activeFile, setActiveFile] = useState<string | null>('frontend/App.tsx');
  const [code, setCode] = useState(SAMPLE_CODE);
  const [terminalOutput, setTerminalOutput] = useState<string[]>([]);
  const [cmd, setCmd] = useState('');
  const [aiAction, setAiAction] = useState<string>('');
  const [isRunning, setIsRunning] = useState(false);

  const toggleDir = (path: string) => {
    setExpandedDirs((prev) => {
      const next = new Set(prev);
      if (next.has(path)) next.delete(path);
      else next.add(path);
      return next;
    });
  };

  const openFile = async (path: string) => {
    setActiveFile(path);
    try {
      const content = await api.files.readFile(path);
      setCode(content);
    } catch {
      setCode(SAMPLE_CODE);
    }
  };

  const runCommand = async () => {
    if (!cmd.trim()) return;
    setTerminalOutput((prev) => [...prev, `$ ${cmd}`]);
    setIsRunning(true);
    try {
      const result: any = await api.system.executeTerminalCommand(cmd);
      setTerminalOutput((prev) => [
        ...prev,
        result.stdout || '',
        ...(result.stderr ? [result.stderr] : []),
        `[Exit: ${result.exitCode}]`,
      ]);
    } catch (err: any) {
      setTerminalOutput((prev) => [...prev, `Error: ${err.message}`]);
    }
    setIsRunning(false);
    setCmd('');
  };

  const runAiAction = async (action: string) => {
    setAiAction(action);
    setTerminalOutput((prev) => [...prev, `\n--- Arcange AI: ${action} ---`]);

    const actions: Record<string, string> = {
      explain: 'Analyzing the current file structure and logic...\nThis component renders a Sparkles icon and heading. It uses React hooks and Tailwind CSS for styling. No external dependencies beyond lucide-react.',
      generate: 'Generated new component:\n\nconst NewFeature = () => (\n  <div className="p-4 bg-white/5 rounded-xl">\n    <p>New feature generated by Arcange AI</p>\n  </div>\n);',
      debug: 'No bugs detected in the current file. All imports are valid and JSX is well-formed.',
      refactor: 'Suggestion: Extract the container div into a reusable Card component for better separation of concerns.',
      test: 'Generated test:\n\ndescribe("ArcangeComponent", () => {\n  it("renders without crashing", () => {\n    render(<ArcangeComponent />);\n    expect(screen.getByText("Arcange AI Assistant")).toBeInTheDocument();\n  });\n});',
    };

    setTimeout(() => {
      setTerminalOutput((prev) => [...prev, actions[action] || 'Action completed.']);
      setAiAction('');
    }, 1500);
  };

  const renderTree = (node: FileNode, depth = 0) => {
    const isExpanded = expandedDirs.has(node.path);
    if (node.type === 'directory') {
      return (
        <div key={node.path}>
          <div
            onClick={() => toggleDir(node.path)}
            className="flex items-center gap-1 px-2 py-1 hover:bg-white/5 cursor-pointer text-sm"
            style={{ paddingLeft: `${depth * 12 + 8}px` }}
          >
            {isExpanded ? <ChevronDown className="w-3 h-3 text-gray-400" /> : <ChevronRight className="w-3 h-3 text-gray-400" />}
            <FolderTree className="w-3.5 h-3.5 text-amber-400" />
            <span className="text-gray-300">{node.name}</span>
          </div>
          {isExpanded && node.children?.map((child) => renderTree(child, depth + 1))}
        </div>
      );
    }
    return (
      <div
        key={node.path}
        onClick={() => openFile(node.path)}
        className={cn(
          'flex items-center gap-1 px-2 py-1 hover:bg-white/5 cursor-pointer text-sm',
          activeFile === node.path && 'bg-blue-500/10 text-blue-300'
        )}
        style={{ paddingLeft: `${depth * 12 + 20}px` }}
      >
        <FileCode className="w-3.5 h-3.5 text-gray-400" />
        <span className={activeFile === node.path ? 'text-blue-300' : 'text-gray-400'}>{node.name}</span>
      </div>
    );
  };

  return (
    <div className="h-full flex">
      {/* File explorer */}
      <div className="w-56 border-r border-white/10 flex flex-col shrink-0">
        <div className="px-3 py-3 border-b border-white/10 flex items-center gap-2">
          <FolderTree className="w-4 h-4 text-amber-400" />
          <span className="text-sm font-semibold text-white">Project Explorer</span>
        </div>
        <div className="flex-1 overflow-y-auto py-1">
          {renderTree(tree)}
        </div>
      </div>

      {/* Code editor + AI sidebar */}
      <div className="flex-1 flex min-w-0">
        <div className="flex-1 flex flex-col min-w-0">
          {/* Editor toolbar */}
          <div className="px-3 py-2 border-b border-white/10 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Code2 className="w-4 h-4 text-blue-400" />
              <span className="text-sm text-gray-300 font-mono">{activeFile || 'No file selected'}</span>
            </div>
            <div className="flex items-center gap-1">
              <AiButton onClick={() => runAiAction('explain')} icon={Sparkles} label="Explain" active={aiAction === 'explain'} />
              <AiButton onClick={() => runAiAction('generate')} icon={FileCode} label="Generate" active={aiAction === 'generate'} />
              <AiButton onClick={() => runAiAction('debug')} icon={Bug} label="Debug" active={aiAction === 'debug'} />
              <AiButton onClick={() => runAiAction('refactor')} icon={RefreshCw} label="Refactor" active={aiAction === 'refactor'} />
              <AiButton onClick={() => runAiAction('test')} icon={TestTube} label="Test" active={aiAction === 'test'} />
              <AiButton onClick={() => runAiAction('run')} icon={Play} label="Run" active={aiAction === 'run'} />
            </div>
          </div>

          {/* Code area */}
          <textarea
            value={code}
            onChange={(e) => setCode(e.target.value)}
            className="flex-1 bg-[#0d0d14] text-gray-200 font-mono text-sm p-4 resize-none focus:outline-none leading-relaxed"
            spellCheck={false}
            placeholder="Select a file or start coding..."
          />

          {/* Terminal */}
          <div className="h-40 border-t border-white/10 bg-[#0a0a0f] flex flex-col">
            <div className="px-3 py-1.5 border-b border-white/10 flex items-center gap-2">
              <TerminalIcon className="w-3.5 h-3.5 text-emerald-400" />
              <span className="text-xs text-gray-400 font-mono">Terminal</span>
              <button
                onClick={() => setTerminalOutput([])}
                className="ml-auto text-xs text-gray-500 hover:text-white"
              >
                Clear
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-3 text-xs font-mono text-gray-400">
              {terminalOutput.map((line, i) => (
                <div key={i} className={cn(line.startsWith('$') && 'text-emerald-400', line.startsWith('Error') && 'text-red-400')}>
                  {line}
                </div>
              ))}
            </div>
            <div className="px-3 py-2 flex items-center gap-2 border-t border-white/10">
              <span className="text-emerald-400 font-mono text-xs">$</span>
              <input
                type="text"
                value={cmd}
                onChange={(e) => setCmd(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && runCommand()}
                placeholder="Run a command..."
                className="flex-1 bg-transparent text-xs font-mono text-white focus:outline-none placeholder-gray-600"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

const AiButton: React.FC<{ onClick: () => void; icon: any; label: string; active: boolean }> = ({ onClick, icon: Icon, label, active }) => (
  <button
    onClick={onClick}
    className={cn(
      'flex items-center gap-1 px-2.5 py-1.5 rounded-lg text-xs font-medium transition',
      active
        ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white'
        : 'bg-white/5 text-gray-400 hover:text-white hover:bg-white/10'
    )}
  >
    <Icon className="w-3 h-3" />
    {label}
  </button>
);
